import { saveScanToHistory } from './scanHistory';

// Generate CSV from report data
export const generateReportsCSV = (reports) => {
  if (!reports || reports.length === 0) return '';
  
  // Define CSV headers
  const headers = ['Product', 'Category', 'Manufacturer', 'NAFDAC Number', 'Status', 'Location', 'Date', 'Similarity Score'];
  
  // Convert reports to CSV rows
  const rows = reports.map(report => [
    `"${report.product || 'N/A'}"`,
    `"${report.category || 'N/A'}"`,
    `"${report.manufacturer || 'N/A'}"`,
    `"${report.nafdacNumber || 'N/A'}"`,
    report.status || 'N/A',
    `"${report.location || 'N/A'}"`,
    report.time || new Date(report.timestamp).toLocaleDateString(),
    report.similarity || 'N/A'
  ]);
  
  // Combine headers and rows
  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.join(','))
  ].join('\n');
  
  return csvContent;
};

// Download CSV file
export const downloadCSV = (data, filename) => {
  const blob = new Blob([data], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  setTimeout(() => {
    URL.revokeObjectURL(url);
  }, 100);
};

// Generate PDF report (simplified version - in production use a proper PDF library)
export const generatePDFReport = (report) => {
  // This is a simplified version - in production, use a library like jsPDF or react-pdf
  const reportHTML = `
    <html>
      <head>
        <title>Counterfeit Report - ${report.product}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 20px; }
          h1 { color: #A020F0; }
          .header { border-bottom: 2px solid #A020F0; padding-bottom: 10px; }
          .section { margin: 20px 0; }
          .label { font-weight: bold; color: #666; }
          .value { margin-left: 10px; }
          .danger { color: #EF4444; }
          .success { color: #10B981; }
          table { width: 100%; border-collapse: collapse; }
          td { padding: 8px; border-bottom: 1px solid #eee; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>SabiLens Counterfeit Report</h1>
          <p>Report ID: ${report.id || `RPT-${Date.now()}`}</p>
          <p>Generated: ${new Date().toLocaleString()}</p>
        </div>
        
        <div class="section">
          <h2>Product Information</h2>
          <table>
            <tr><td class="label">Product Name:</td><td>${report.product || 'N/A'}</td></tr>
            <tr><td class="label">Category:</td><td>${report.category || 'N/A'}</td></tr>
            <tr><td class="label">Manufacturer:</td><td>${report.manufacturer || 'N/A'}</td></tr>
            <tr><td class="label">NAFDAC Number:</td><td>${report.nafdacNumber || 'N/A'}</td></tr>
            <tr><td class="label">Batch Number:</td><td>${report.batchNumber || 'N/A'}</td></tr>
          </table>
        </div>
        
        <div class="section">
          <h2>Scan Details</h2>
          <table>
            <tr><td class="label">Status:</td><td class="${report.status === 'fake' ? 'danger' : report.status === 'caution' ? 'warning' : 'success'}">${report.status || 'N/A'}</td></tr>
            <tr><td class="label">Similarity Score:</td><td>${report.similarity || 0}%</td></tr>
            <tr><td class="label">Location:</td><td>${report.location || 'N/A'}</td></tr>
            <tr><td class="label">Date/Time:</td><td>${report.time || new Date(report.timestamp).toLocaleString()}</td></tr>
          </table>
        </div>
        
        ${report.issues ? `
        <div class="section">
          <h2>Issues Detected</h2>
          <ul>
            ${report.issues.map(issue => `<li>${issue}</li>`).join('')}
          </ul>
        </div>
        ` : ''}
        
        <div class="section">
          <p><em>This report was generated by SabiLens AI counterfeit detection system.</em></p>
        </div>
      </body>
    </html>
  `;
  
  return reportHTML;
};

// Create a ZIP file with multiple files (simulated - in production use JSZip)
export const createEvidenceZip = async (caseId, evidenceFiles) => {
  // This is a simulation - in production, you would use JSZip to create actual ZIP files
  console.log(`Creating ZIP for case ${caseId} with ${evidenceFiles.length} files`);
  
  // Simulate ZIP creation delay
  await new Promise(resolve => setTimeout(resolve, 1500));
  
  return {
    success: true,
    caseId,
    fileCount: evidenceFiles.length,
    size: `${(evidenceFiles.length * 2.5).toFixed(1)} MB`
  };
};

// Download single file
export const downloadFile = (content, filename, type = 'text/html') => {
  const blob = new Blob([content], { type });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  setTimeout(() => {
    URL.revokeObjectURL(url);
  }, 100);
};

// Export reports as CSV
export const exportReports = (reports, filename = 'counterfeit-reports.csv') => {
  const csv = generateReportsCSV(reports);
  downloadCSV(csv, filename);
};

// Export single report as PDF
export const exportReportAsPDF = (report) => {
  const html = generatePDFReport(report);
  downloadFile(html, `report-${report.product || 'product'}-${Date.now()}.html`, 'text/html');
};

// Get mock evidence files for a case
export const getEvidenceFiles = (caseId) => {
  // Mock evidence files - in production, these would come from an API
  return [
    {
      id: 1,
      name: 'product-front.jpg',
      type: 'image',
      size: '2.4 MB',
      url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400'
    },
    {
      id: 2,
      name: 'product-back.jpg',
      type: 'image',
      size: '1.8 MB',
      url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400'
    },
    {
      id: 3,
      name: 'receipt.jpg',
      type: 'image',
      size: '1.2 MB',
      url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400'
    },
    {
      id: 4,
      name: 'forensic-report.pdf',
      type: 'pdf',
      size: '856 KB'
    },
    {
      id: 5,
      name: 'scan-analysis.json',
      type: 'json',
      size: '124 KB'
    }
  ];
};